version: 43.0.9
pageUuid: b33e60c0-116d-11ea-8c85-a368dd700d7c
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.106.0
